### ISSUE TITLE
Date Translation that would fit all arabic tens, gender and plurality rules 

### ISSUE THREAD

**Issue by jeaneldebs** [ocpsoft/prettytime#125]
Hello,
I should start by explaining a little about arabic and its many grammar “rules",
Arabic unlike english has many date rules of plurality and gender. 

So using Ago(مضت) as a date suffix, would sound very wrong in arabic because of many gender and plural rule, also because some dates are referred to in masculine ,other in feminine.
Below is an example:
- 2 weeks ago —>  ٢ أسابيع مضت   

           ("أسابيع" is a feminine noun)
- Week ago —>  أسبوع مضى 

           ("أسبوع" is a masculine noun)

So  "Ago"(مضت) is  correct for Weeks(أسابيع) but not for Week(أسبوع)

Therefore, if it's possible,  we prefer using From(منذ) as a date prefix which can basically fit all dates
- 2 weeks ago —>  منذ 2 أسابيع
- Week ago —>  منذ أسبوع 

Can anyone check that?
Thanks in advance.

**Comment by MenoData** [comment]
I am not known to Arabic, but I have taken following data from CLDR-v28 for outputting relative times in my own time library, see here for content comparison: 

https://github.com/MenoData/Time4J/blob/master/i18n/src/main/resources/reltime/relpattern_ar.properties

**Comment by jeaneldebs** [comment]
Thanks for your quick reply. 

I checked the file and it seems that it was updated
There is a difference between your own time library and the file.

In the file they use: 

- `قبل` (same as `منذ`) as prefix for past times. 
  - Could be applied in all cases(plural/singular or masculine/feminine dates) 
- `خلال` (better to use `بعد`) as prefix for future times.
  - Could be applied in all cases

In your own library, you use:
- `مضت` (ago) as prefix for past times.
  - Could not be applied in all cases
- `من الآن`(from now) as prefix for future times.

**Example:**
in your file: `2 weeks ago --> ٢ أسابيع مضت `
in the file: `2 weeks ago --> قبل ٢ أسبوع`

**Comment by MenoData** [comment]
I am not quite sure if you have misinterpreted how my library prints "2 weeks ago". Therefore this clarification: It will print قبل أسبوعين and not ٢ أسابيع مضت (CLDR-data don't define a placeholder for the number 2, but seem to have an extra word for it). A quick online translator check seems to confirm this version, for example http://dictionary.reverso.net/arabic-english/قبل%20أسبوعين/forced.

In general, I have taken the data from CLDR and still think that these data - although surely not perfect - are somehow trustworthy due to the bigger community background and support by big enterprises like IBM. Plural rules for Arabic (maybe containing the gender case here - I am not familiar to Arabic) are taken into account, and CLDR defines 6! plural rules, not just singular and plural. If you think that CLDR-data for Arabic are wrong then please file an issue there (and show some credits and references).

**Comment by lincolnthree** [comment]
Hey @MenoData,

Your proposal is interesting, and I do think that trying to use some more standard translations is probably a good idea. I'd be happy to review a pull request that tries to incorporate these concepts. In general, user-submitted data is how open-source works best :) That goes for improvements as well.

Cheers!
~Lincoln
