### ISSUE TITLE
There should not be spaces between Chinese characters.

### ISSUE THREAD

**Issue by drakeet** [ocpsoft/prettytime#139]
Your library is pretty cool! But when I use `prettyTime.format(date)` with the `Resources_zh.java`, I get the wrong format result:

`2 天 前` / `3 分钟 前` 

There should not be spaces before the suffix `前`. `前` is a `DayPastSuffix`. They should be: 

`2 天前` / `3 分钟前`

I use the version 4.0.1-final. How can I remove the space? 

Thanks!

**Comment by Dart2112** [comment]
as a quick fix, you could just remove the spaces in java by replacing all " " with ""

**Comment by lincolnthree** [comment]
This can be handled using a custom `SimpleTimeFormat`. Or a PR can be submitted to allow the Chinese language bundle to provide its own `TimeFormat` instance that handles this.

Example: https://github.com/ocpsoft/prettytime/blob/master/core/src/main/java/org/ocpsoft/prettytime/i18n/Resources_de.java#L131

***Issue cleanup*** Thanks for filing this issue. We are cleaning old issues from the repository. If the issue is still reproducible, please re-open with a test case to reproduce the behavior.
