### ISSUE TITLE
Supports for epoch values in NLP

### ISSUE THREAD

**Issue by praveendath92** [ocpsoft/prettytime#144]
Epoch values are definitely not a natural language but it would be nice to support them in `NLP Parser` so that all different ways a data time may be expressed is supported by the parser.

**Comment by lincolnthree** [comment]
NLP is provided by the `org.joestelmach.natty` package. Feature enhancements to NLP should be submitted there:  https://github.com/joestelmach/natty

***Issue cleanup*** Thanks for filing this issue. We are cleaning old issues from the repository. If the issue is still reproducible, please re-open with a test case to reproduce the behavior.
