### ISSUE TITLE
[QUESTION] How can i build a custom format with only the date?

### ISSUE THREAD

**Issue by sk8darr** [ocpsoft/prettytime#154]
Is this possible? Can we use this library with a "dd/MM/yyyy" date format instead "dd/MM/yyyy hh:mm:ss"

Thanks in advance!

**Comment by lincolnthree** [comment]
Thanks for the question! I do not believe this is something `PrettyTime` is intended to do. Closing as WonFix.

***Issue cleanup*** Thanks for filing this issue. We are cleaning old issues from the repository. If the issue is still reproducible, please re-open with a test case to reproduce the behavior.
