### ISSUE TITLE
error in parsing the date format MM/yyyy

### ISSUE THREAD

**Issue by rssdev10** [ocpsoft/prettytime#196]
Dates in a format MM/yyyy like 01/2001, 01/2017, etc, are parsed as dates with two digits year only.

```
new PrettyTimeParser().parseSyntax("01/2001")
```
gives:
```
dates -> Mon Jan 20 19:04:22 UTC 2020
text = 01/20

```

Any 20xx year gives 20 only.

Library version:  'org.ocpsoft.prettytime:prettytime-nlp:4.0.5.Final'

**Comment by lincolnthree** [comment]
Issues with NLP should be reported to: https://github.com/joestelmach/natty

NOTE: This may be fixed in PrettyTime 5.0.0, as we've updated to Natty 0.13.0.


***Issue cleanup*** Thanks for filing this issue. We are cleaning old issues from the repository. If the issue is still reproducible, please re-open with a test case to reproduce the behavior.
